trigger:
- main

stages:
- stage: Linux
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: TestJobLinux
    steps:
    - task: BicepInstall@1
      displayName: 'Install Bicep CLI test'

    - task: BicepBuild@1
      displayName: 'Compile Sample .bicep files test'
      inputs:
        sourceDirectory: 'bicep_files/**.bicep'

    - script: 'ls -la bicep_files'
      displayName: 'List source and generated files'

- stage: Windows
  pool:
    vmImage: 'windows-latest'
  jobs:
  - job: TestJobWindows
    steps:
    - task: BicepInstall@1
      displayName: 'Install Bicep CLI test'

    - task: BicepBuild@1
      displayName: 'Compile Sample .bicep files test'
      inputs:
        sourceDirectory: 'bicep_files/**.bicep'

    - script: 'Get-ChildItem -Path bicep_files'
      displayName: 'List source and generated files'

- stage: macOS
  pool:
    vmImage: 'macOS-latest'
  jobs:
  - job: TestJobMacOS
    steps:
    - task: BicepInstall@1
      displayName: 'Install Bicep CLI test'

    - task: BicepBuild@1
      displayName: 'Compile Sample .bicep files test'
      inputs:
        sourceDirectory: 'bicep_files/**.bicep'

    - script: 'ls -la bicep_files'
      displayName: 'List source and generated files'
