trigger:
- main

stages:
- stage: Linux
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: TestJobLinux
    steps:
    - task: BicepInstall@0
      displayName: 'Install Bicep CLI test'

    - task: BicepBuild@0
      displayName: 'Compile Sample .bicep files test (defaults with dir)'
      inputs:
        sourceDirectory: 'bicep_files/'

    - task: BicepBuild@0
      displayName: 'Compile Sample .bicep files test (defaults with glob)'
      inputs:
        sourceDirectory: 'bicep_files/**.bicep'

    - task: BicepBuild@0
      displayName: 'Compile Sample .bicep files test (all in entire directory tree with glob)'
      inputs:
        sourceDirectory: '**/**.bicep'

    - task: BicepBuild@0
      displayName: 'Compile Sample .bicep files test (with output directory)'
      inputs:
        process: 'multiple'
        sourceDirectory: 'bicep_files/**.bicep'
        outputDirectory: 'bicep_files/out'

    - task: BicepBuild@0
      displayName: 'Compile Sample .bicep files test (with stdout output)'
      inputs:
        process: 'multiple'
        sourceDirectory: 'bicep_files/**.bicep'
        stdout: true

    - task: BicepBuild@0
      displayName: 'Compile Sample .bicep file test (defaults)'
      inputs:
        process: 'single'
        sourceFile: './bicep_files/sample1.bicep'

    - task: BicepBuild@0
      displayName: 'Compile Sample .bicep file test (with output filename)'
      inputs:
        process: 'single'
        sourceFile: './bicep_files/sample1.bicep'
        stdout: false
        outputFile: './bicep_files/sample1.out.json'

    - task: BicepBuild@0
      displayName: 'Compile Sample .bicep file test (with stdout output)'
      inputs:
        process: 'single'
        sourceFile: './bicep_files/sample1.bicep'
        stdout: true

    - script: 'ls -laR bicep_files'
      displayName: 'List source and generated files'

    - script: 'mv bicep_files "bicep files"'
      displayName: 'Move to other directory with special chars'

    - task: BicepBuild@0
      displayName: 'Compile Sample .bicep files test 2'
      inputs:
        sourceDirectory: 'bicep files/**.bicep'

    - script: 'ls -laR "bicep files"'
      displayName: 'List source and generated files'

    - task: BicepDecompile@0
      displayName: 'Decompile Sample .json files test (defaults with dir)'
      inputs:
        sourceDirectory: 'arm_templates/'

    - task: BicepDecompile@0
      displayName: 'Decompile Sample .json files test (defaults with glob)'
      inputs:
        sourceDirectory: 'arm_templates/**.json'

    - task: BicepDecompile@0
      displayName: 'Decompile Sample .json files test (all in entire directory tree with glob)'
      inputs:
        sourceDirectory: '**/**.json'

    - task: BicepDecompile@0
      displayName: 'Decompile Sample .json files test (with output directory)'
      inputs:
        process: 'multiple'
        sourceDirectory: 'arm_templates/**.json'
        outputDirectory: 'arm_templates/out'

    - task: BicepDecompile@0
      displayName: 'Decompile Sample .json files test (with stdout output)'
      inputs:
        process: 'multiple'
        sourceDirectory: 'arm_templates/**.json'
        stdout: true

    - task: BicepDecompile@0
      displayName: 'Decompile Sample .json file test (defaults)'
      inputs:
        process: 'single'
        sourceFile: './arm_templates/arm_storage_account.json'

    - task: BicepDecompile@0
      displayName: 'Decompile Sample .json file test (with output filename)'
      inputs:
        process: 'single'
        sourceFile: './arm_templates/arm_storage_account.json'
        stdout: false
        outputFile: './arm_templates/sample1.out.bicep'

    - task: BicepDecompile@0
      displayName: 'Decompile Sample .json file test (with stdout output)'
      inputs:
        process: 'single'
        sourceFile: './arm_templates/arm_storage_account.json'
        stdout: true

    - script: 'ls -laR arm_templates'
      displayName: 'List source and generated files'

    - script: 'mv arm_templates "arm templates"'
      displayName: 'Move to other directory with special chars'

    - task: BicepDecompile@0
      displayName: 'Decompile Sample .json files test 2'
      inputs:
        sourceDirectory: 'arm templates/**.json'

    - script: 'ls -laR "arm templates"'
      displayName: 'List source and generated files'

- stage: Windows
  pool:
    vmImage: 'windows-latest'
  jobs:
  - job: TestJobWindows
    steps:
    - task: BicepInstall@0
      displayName: 'Install Bicep CLI test'

    - task: BicepBuild@0
      displayName: 'Compile Sample .bicep files test (defaults with dir)'
      inputs:
        sourceDirectory: 'bicep_files/'

    - task: BicepBuild@0
      displayName: 'Compile Sample .bicep files test (defaults with glob)'
      inputs:
        sourceDirectory: 'bicep_files/**.bicep'

    - task: BicepBuild@0
      displayName: 'Compile Sample .bicep files test (all in entire directory tree with glob)'
      inputs:
        sourceDirectory: '**/**.bicep'

    - task: BicepBuild@0
      displayName: 'Compile Sample .bicep files test (with output directory)'
      inputs:
        process: 'multiple'
        sourceDirectory: 'bicep_files\**.bicep'
        outputDirectory: 'bicep_files\out'

    - task: BicepBuild@0
      displayName: 'Compile Sample .bicep files test (with stdout output)'
      inputs:
        process: 'multiple'
        sourceDirectory: 'bicep_files\**.bicep'
        stdout: true

    - task: BicepBuild@0
      displayName: 'Compile Sample .bicep file test (defaults)'
      inputs:
        process: 'single'
        sourceFile: '.\bicep_files\sample1.bicep'

    - task: BicepBuild@0
      displayName: 'Compile Sample .bicep file test (with output filename)'
      inputs:
        process: 'single'
        sourceFile: '.\bicep_files\sample1.bicep'
        stdout: false
        outputFile: '.\bicep_files\sample1.out.json'

    - task: BicepBuild@0
      displayName: 'Compile Sample .bicep file test (with stdout output)'
      inputs:
        process: 'single'
        sourceFile: '.\bicep_files\sample1.bicep'
        stdout: true

    - script: 'dir /s bicep_files'
      displayName: 'List source and generated files'

    - script: 'move bicep_files "bicep files"'
      displayName: 'Move to other directory with special chars'

    - task: BicepBuild@0
      displayName: 'Compile Sample .bicep files test 2'
      inputs:
        sourceDirectory: 'bicep files/**.bicep'

    - script: 'dir /s "bicep files"'
      displayName: 'List source and generated files'

    - task: BicepDecompile@0
      displayName: 'Decompile Sample .json files test (defaults with dir)'
      inputs:
        sourceDirectory: 'arm_templates/'

    - task: BicepDecompile@0
      displayName: 'Decompile Sample .json files test (defaults with glob)'
      inputs:
        sourceDirectory: 'arm_templates/**.json'

    - task: BicepDecompile@0
      displayName: 'Decompile Sample .json files test (all in entire directory tree with glob)'
      inputs:
        sourceDirectory: '**/**.json'

    - task: BicepDecompile@0
      displayName: 'Decompile Sample .json files test (with output directory)'
      inputs:
        process: 'multiple'
        sourceDirectory: 'arm_templates/**.json'
        outputDirectory: 'arm_templates/out'

    - task: BicepDecompile@0
      displayName: 'Decompile Sample .json files test (with stdout output)'
      inputs:
        process: 'multiple'
        sourceDirectory: 'arm_templates/**.json'
        stdout: true

    - task: BicepDecompile@0
      displayName: 'Decompile Sample .json file test (defaults)'
      inputs:
        process: 'single'
        sourceFile: './arm_templates/arm_storage_account.json'

    - task: BicepDecompile@0
      displayName: 'Decompile Sample .json file test (with output filename)'
      inputs:
        process: 'single'
        sourceFile: './arm_templates/arm_storage_account.json'
        stdout: false
        outputFile: './arm_templates/sample1.out.bicep'

    - task: BicepDecompile@0
      displayName: 'Decompile Sample .json file test (with stdout output)'
      inputs:
        process: 'single'
        sourceFile: './arm_templates/arm_storage_account.json'
        stdout: true

    - script: 'dir /s arm_templates'
      displayName: 'List source and generated files'

    - script: 'move arm_templates "arm templates"'
      displayName: 'Move to other directory with special chars'

    - task: BicepDecompile@0
      displayName: 'Decompile Sample .json files test 2'
      inputs:
        sourceDirectory: 'arm templates/**.json'

    - script: 'dir /s "arm templates"'
      displayName: 'List source and generated files'

- stage: macOS
  pool:
    vmImage: 'macOS-latest'
  jobs:
  - job: TestJobMacOS
    steps:
    - task: BicepInstall@0
      displayName: 'Install Bicep CLI test'

    - task: BicepBuild@0
      displayName: 'Compile Sample .bicep files test (defaults with dir)'
      inputs:
        sourceDirectory: 'bicep_files/'

    - task: BicepBuild@0
      displayName: 'Compile Sample .bicep files test (defaults with glob)'
      inputs:
        sourceDirectory: 'bicep_files/**.bicep'

    - task: BicepBuild@0
      displayName: 'Compile Sample .bicep files test (all in entire directory tree with glob)'
      inputs:
        sourceDirectory: '**/**.bicep'

    - task: BicepBuild@0
      displayName: 'Compile Sample .bicep files test (with output directory)'
      inputs:
        process: 'multiple'
        sourceDirectory: 'bicep_files/**.bicep'
        outputDirectory: 'bicep_files/out'

    - task: BicepBuild@0
      displayName: 'Compile Sample .bicep files test (with stdout output)'
      inputs:
        process: 'multiple'
        sourceDirectory: 'bicep_files/**.bicep'
        stdout: true

    - task: BicepBuild@0
      displayName: 'Compile Sample .bicep file test (defaults)'
      inputs:
        process: 'single'
        sourceFile: './bicep_files/sample1.bicep'

    - task: BicepBuild@0
      displayName: 'Compile Sample .bicep file test (with output filename)'
      inputs:
        process: 'single'
        sourceFile: './bicep_files/sample1.bicep'
        stdout: false
        outputFile: './bicep_files/sample1.out.json'

    - task: BicepBuild@0
      displayName: 'Compile Sample .bicep file test (with stdout output)'
      inputs:
        process: 'single'
        sourceFile: './bicep_files/sample1.bicep'
        stdout: true

    - script: 'ls -laR bicep_files'
      displayName: 'List source and generated files'

    - script: 'mv bicep_files "bicep files"'
      displayName: 'Move to other directory with special chars'

    - task: BicepBuild@0
      displayName: 'Compile Sample .bicep files test 2'
      inputs:
        sourceDirectory: 'bicep files/**.bicep'

    - script: 'ls -laR "bicep files"'
      displayName: 'List source and generated files'

    - task: BicepDecompile@0
      displayName: 'Decompile Sample .json files test (defaults with dir)'
      inputs:
        sourceDirectory: 'arm_templates/'

    - task: BicepDecompile@0
      displayName: 'Decompile Sample .json files test (defaults with glob)'
      inputs:
        sourceDirectory: 'arm_templates/**.json'

    - task: BicepDecompile@0
      displayName: 'Decompile Sample .json files test (all in entire directory tree with glob)'
      inputs:
        sourceDirectory: '**/**.json'

    - task: BicepDecompile@0
      displayName: 'Decompile Sample .json files test (with output directory)'
      inputs:
        process: 'multiple'
        sourceDirectory: 'arm_templates/**.json'
        outputDirectory: 'arm_templates/out'

    - task: BicepDecompile@0
      displayName: 'Decompile Sample .json files test (with stdout output)'
      inputs:
        process: 'multiple'
        sourceDirectory: 'arm_templates/**.json'
        stdout: true

    - task: BicepDecompile@0
      displayName: 'Decompile Sample .json file test (defaults)'
      inputs:
        process: 'single'
        sourceFile: './arm_templates/arm_storage_account.json'

    - task: BicepDecompile@0
      displayName: 'Decompile Sample .json file test (with output filename)'
      inputs:
        process: 'single'
        sourceFile: './arm_templates/arm_storage_account.json'
        stdout: false
        outputFile: './arm_templates/sample1.out.bicep'

    - task: BicepDecompile@0
      displayName: 'Decompile Sample .json file test (with stdout output)'
      inputs:
        process: 'single'
        sourceFile: './arm_templates/arm_storage_account.json'
        stdout: true

    - script: 'ls -laR arm_templates'
      displayName: 'List source and generated files'

    - script: 'mv arm_templates "arm templates"'
      displayName: 'Move to other directory with special chars'

    - task: BicepDecompile@0
      displayName: 'Decompile Sample .json files test 2'
      inputs:
        sourceDirectory: 'arm templates/**.json'

    - script: 'ls -laR "arm templates"'
      displayName: 'List source and generated files'